-- 005: all EU member states as regions, with Eurostat and World Bank codes.

INSERT INTO ref.region (code, label, kind, composition) VALUES
  ('AT', 'Austria', 'country', 'n/a'),
  ('BE', 'Belgium', 'country', 'n/a'),
  ('BG', 'Bulgaria', 'country', 'n/a'),
  ('CY', 'Cyprus', 'country', 'n/a'),
  ('CZ', 'Czechia', 'country', 'n/a'),
  ('DK', 'Denmark', 'country', 'n/a'),
  ('EE', 'Estonia', 'country', 'n/a'),
  ('EL', 'Greece', 'country', 'n/a'),
  ('FI', 'Finland', 'country', 'n/a'),
  ('HR', 'Croatia', 'country', 'n/a'),
  ('HU', 'Hungary', 'country', 'n/a'),
  ('IE', 'Ireland', 'country', 'n/a'),
  ('LT', 'Lithuania', 'country', 'n/a'),
  ('LU', 'Luxembourg', 'country', 'n/a'),
  ('LV', 'Latvia', 'country', 'n/a'),
  ('MT', 'Malta', 'country', 'n/a'),
  ('NL', 'Netherlands', 'country', 'n/a'),
  ('PL', 'Poland', 'country', 'n/a'),
  ('PT', 'Portugal', 'country', 'n/a'),
  ('RO', 'Romania', 'country', 'n/a'),
  ('SE', 'Sweden', 'country', 'n/a'),
  ('SI', 'Slovenia', 'country', 'n/a'),
  ('SK', 'Slovakia', 'country', 'n/a')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ref.region_alias (system, source_code, region_code, note) VALUES
  ('ESTAT', 'AT', 'AT', NULL),
  ('ESTAT', 'BE', 'BE', NULL),
  ('ESTAT', 'BG', 'BG', NULL),
  ('ESTAT', 'CY', 'CY', NULL),
  ('ESTAT', 'CZ', 'CZ', NULL),
  ('ESTAT', 'DK', 'DK', NULL),
  ('ESTAT', 'EE', 'EE', NULL),
  ('ESTAT', 'EL', 'EL', NULL),
  ('ESTAT', 'FI', 'FI', NULL),
  ('ESTAT', 'HR', 'HR', NULL),
  ('ESTAT', 'HU', 'HU', NULL),
  ('ESTAT', 'IE', 'IE', NULL),
  ('ESTAT', 'LT', 'LT', NULL),
  ('ESTAT', 'LU', 'LU', NULL),
  ('ESTAT', 'LV', 'LV', NULL),
  ('ESTAT', 'MT', 'MT', NULL),
  ('ESTAT', 'NL', 'NL', NULL),
  ('ESTAT', 'PL', 'PL', NULL),
  ('ESTAT', 'PT', 'PT', NULL),
  ('ESTAT', 'RO', 'RO', NULL),
  ('ESTAT', 'SE', 'SE', NULL),
  ('ESTAT', 'SI', 'SI', NULL),
  ('ESTAT', 'SK', 'SK', NULL),
  ('WB', 'AUT', 'AT', NULL),
  ('WB', 'BEL', 'BE', NULL),
  ('WB', 'BGR', 'BG', NULL),
  ('WB', 'CYP', 'CY', NULL),
  ('WB', 'CZE', 'CZ', NULL),
  ('WB', 'DEU', 'DE', NULL),
  ('WB', 'DNK', 'DK', NULL),
  ('WB', 'EST', 'EE', NULL),
  ('WB', 'GRC', 'EL', NULL),
  ('WB', 'ESP', 'ES', NULL),
  ('WB', 'FIN', 'FI', NULL),
  ('WB', 'FRA', 'FR', NULL),
  ('WB', 'HRV', 'HR', NULL),
  ('WB', 'HUN', 'HU', NULL),
  ('WB', 'IRL', 'IE', NULL),
  ('WB', 'ITA', 'IT', NULL),
  ('WB', 'LTU', 'LT', NULL),
  ('WB', 'LUX', 'LU', NULL),
  ('WB', 'LVA', 'LV', NULL),
  ('WB', 'MLT', 'MT', NULL),
  ('WB', 'NLD', 'NL', NULL),
  ('WB', 'POL', 'PL', NULL),
  ('WB', 'PRT', 'PT', NULL),
  ('WB', 'ROU', 'RO', NULL),
  ('WB', 'SWE', 'SE', NULL),
  ('WB', 'SVN', 'SI', NULL),
  ('WB', 'SVK', 'SK', NULL),
  ('WB', 'EUU', 'EU27_2020', 'World Bank aggregate European Union')
ON CONFLICT (system, source_code) DO NOTHING;
